name: Build Job Pairs
on: workflow_dispatch

jobs:
  build:
    name: Generate job pair for non-PR job
    runs-on: ubuntu-22.04
    steps:
       - uses: actions/checkout@v3
         with:
          token: ${{ secrets.GH_TOKEN }}
       - run: |
          git config --local user.email "20823498+guan-kevin@users.noreply.github.com"
          git config --local user.name "guan-kevin"
       - run: |
          echo '1' > status.txt 
          git add .
          git commit -m "Generated failed run"
          git push
       - name: Push changes
         uses: ad-m/github-push-action@master
         with:
            branch: main
       - run: |
          echo '0' > status.txt 
          git add .
          git commit -m "Generated passed run"
          git push
       - name: Push changes
         uses: ad-m/github-push-action@master
         with:
            branch: main
            github_token: ${{ secrets.GH_TOKEN }}
