name: Test
on: workflow_dispatch

jobs:
  test:
    name: Test
    runs-on: self-hosted
    container:
      image: bugswarm/images:ubuntu-20.04
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - run: |
          rm /usr/bin/python3
          ln -s /usr/bin/python3.8 /usr/bin/python3
      - run: |
          sudo apt-get --assume-yes install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
          sudo apt-get --assume-yes update
          sudo apt-get --assume-yes install docker-ce
          sudo usermod -aG docker $(whoami)
          su $(whoami)
      - run: docker ps -a
  
