name: Test
on: workflow_dispatch

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    container:
      image: bugswarm/images:ubuntu-20.04
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - run: docker ps -a
  
