name: Main
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup 1
        run: echo "Setup 1 OK"
      - name: Setup 2
        run: echo "Setup 2 OK"
      - name: Run test 1
        continue-on-error: true
        run: echo "Test 1" && exit 255
      - name: Run test 2
        continue-on-error: true
        run: echo "Test 2"
