name: Main
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run shell script
        run: |
          echo 'Hello world'
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Run python script
        run: |
          python test.py

  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: green
          - color: pink
            animal: cat
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat
    steps:
      - name: Run shell script
        run: |
          echo 'Hello world'
          echo 'From ${{ matrix.fruit }}'
          exit 1
