name: Main
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Hello world action step
        id: hello
        uses: guan-kevin/javascript-action@v1
        with:
          who-to-greet: 'guan-kevin'
      - name: Bye world action step
        id: bye
        uses: guan-kevin/javascript-action/bye@v1
        with:
          who-to-greet: 'guan-kevin'
