name: Main
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Fake Setup 1
        run: exit 1
      - name: Fake Setup 2
        id: final_setup
        run: exit 2
      - name: Run test 1
        if: steps.final_setup.conclusion == 'success'
        run: echo "Test 1"
      - name: Run test 2
        if: steps.final_setup.conclusion == 'success'
        run: echo "Test 2"
