on:
  push:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: 'reproducer'

jobs:
  test:
    name: Test Pipeline
    runs-on: [self-hosted, s]
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ github.workspace }}"
      - run: sudo ls -lia ${{ github.workspace }}
