on:
  push:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: 'reproducer'

jobs:
  test:
    name: Test Pipeline
    runs-on: ubuntu-latest
    steps:
      - run: echo "Branch is ${{ inputs.branch }}"
