name: Reproducer Test
on: [push, pull_request]

env:
  workflow_ENV_1: Workflow Env 1
  workflow_ENV_2: Workflow Env 2
  workflow_ENV_3: Workflow Env 3

jobs:
  test-all:
    name: Test Reproducer
    runs-on: ubuntu-20.04
    env:
      job_ENV_1: Job Env 1
      job_ENV_2: Job Env 2
      workflow_ENV_2: Job Env 3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
      - name: Set Up Test Environment
        run: |
          mkdir test
          echo "LARGER_THAN_0=1" >> $GITHUB_ENV
          echo "larger_than_0=2" >> $GITHUB_ENV
          echo 'SMALLER_THAN_0<<1!@#$aA[];|\~`.,?/+-)(*&^%<>' >> $GITHUB_ENV
          echo "-1" >> $GITHUB_ENV
          echo '1!@#$aA[];|\~`.,?/+-)(*&^%<>' >> $GITHUB_ENV
      - name: Test Environment Variables
        env:
          step_ENV_1: Step Env 1
          job_ENV_2: Step Env 2
          workflow_ENV_3: Step Env 3
        run: |
          if [[ $workflow_ENV_1 != "Workflow Env 1" ]]; then
            echo "Incorrect workflow_ENV_1" && exit 1
          fi
          if [[ $workflow_ENV_2 != "Job Env 3" ]]; then
            echo "Incorrect workflow_ENV_2" && exit 1
          fi
          if [[ $workflow_ENV_3 != "Step Env 3" ]]; then
            echo "Incorrect workflow_ENV_3" && exit 1
          fi
          if [[ $job_ENV_1 != "Job Env 1" ]]; then
            echo "Incorrect job_ENV_1" && exit 1
          fi
          if [[ $job_ENV_2 != "Step Env 2" ]]; then
            echo "Incorrect job_ENV_2" && exit 1
          fi
          if [[ $step_ENV_1 != "Step Env 1" ]]; then
            echo "Incorrect step_ENV_1" && exit 1
          fi
          if [[ $LARGER_THAN_0 != 1 ]]; then
            echo "Incorrect LARGER_THAN_0" && exit 1
          fi
          if [[ $larger_than_0 != 2 ]]; then
            echo "Incorrect larger_than_0" && exit 1
          fi
          if [[ $SMALLER_THAN_0 != -1 ]]; then
            echo "Incorrect SMALLER_THAN_0" && exit 1
          fi
          echo "Test Environment Variables OK!"
      - name: Test shell and working-directory
        run: |
          import os
          if not os.getcwd().endswith('/test'):
            print("Incorrect working directory")
            exit(1);
          print("Test shell and working-directory OK")
        shell: python
        working-directory: test
      - name: Test if statement using not equal
        if: ${{ env.LARGER_THAN_0 != 1 }}
        run: |
          echo "LARGER_THAN_0 != 1" && exit 1
      - name: Test if statement using not equal without {{ }}
        if: env.LARGER_THAN_0 != 1
        run: |
          echo "LARGER_THAN_0 != 1" && exit 1
      - name: Test if statement using less than
        id: test_less_than
        if: ${{ env.SMALLER_THAN_0 < 0 }}
        run: echo "test_less_than=1" >> $GITHUB_ENV
      - name: Test if statement using less than or equal
        id: test_less_than_or_equal
        if: ${{ env.SMALLER_THAN_0 <= -1 }}
        run: echo "test_less_than_or_equal=1" >> $GITHUB_ENV
      - name: Test if statement using greater than
        id: test_greater_than
        if: ${{ env.SMALLER_THAN_0 > -2 }}
        run: echo "test_greater_than=1" >> $GITHUB_ENV
      - name: Test if statement using greater than or equal
        id: test_greater_than_or_equal
        if: ${{ env.SMALLER_THAN_0 >= -1 }}
        run: echo "test_greater_than_or_equal=1" >> $GITHUB_ENV
      - name: Test if statement using equal
        id: test_equal
        if: ${{ env.SMALLER_THAN_0 == -1 }}
        run: echo "test_equal=1" >> $GITHUB_ENV
      - name: Test if statement using not
        id: test_not
        if: ${{ !(env.SMALLER_THAN_0 == 0) }}
        run: echo "test_not=1" >> $GITHUB_ENV
      - name: Test if statement using and
        id: test_and
        if: ${{ $LARGER_THAN_0 == 1 && $SMALLER_THAN_0 == -1 }}
        run: echo "test_and=1" >> $GITHUB_ENV
      - name: Test if statement using or
        id: test_and
        if: ${{ $LARGER_THAN_0 == 0 || $SMALLER_THAN_0 == -1 }}
        run: echo "test_or=1" >> $GITHUB_ENV
      - name: Checking test result
        run: |
          if [[ $test_less_than != 1 ]]; then
            echo "Incorrect test_less_than" && exit 1
          elif [[ $test_less_than_or_equal != 1 ]]; then
            echo "Incorrect test_less_than_or_equal" && exit 1
          elif [[ $test_greater_than != 1 ]]; then
            echo "Incorrect test_greater_than" && exit 1
          elif [[ $test_greater_than_or_equal != 1 ]]; then
            echo "Incorrect test_greater_than_or_equal" && exit 1
          elif [[ $test_equal != 1 ]]; then
            echo "Incorrect test_equal" && exit 1
          elif [[ $test_not != 1 ]]; then
            echo "Incorrect test_not" && exit 1
          elif [[ $test_and != 1 ]]; then
            echo "Incorrect test_and" && exit 1
          elif [[ $test_or != 1 ]]; then
            echo "Incorrect test_or" && exit 1
          fi
  test-defaults:
    name: Test Reproducer (defaults)
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: python
        working-directory: python
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
      - uses: actions/checkout@v3
      - name: Test defaults.run.shell and defaults.run.working-directory
        run: |
          import os
          if not os.getcwd().endswith('/python'):
            print("Incorrect working directory")
            exit(1);
          print("Test defaults.run.shell and defaults.run.working-directory OK")
      - name: Test Override shell
        run: |
          cd ..
          mkdir test
          echo "Test Override shell OK"
        shell: bash
      - name: Test override working-directory
        run: |
          import os
          if not os.getcwd().endswith('/test'):
            print("Incorrect working directory")
            exit(1);
          print("Test working-directory OK")
        working-directory: test
        
